### PR TITLE
Upgrade to Ruby 2.7

### PR DESCRIPTION
**Pull request by paulfioravanti**
These code changes have been a bit of an exercise in Buildkite frustration. At this point, I do not understand why it would seem to be ignoring the values present in the `CI`, or any other, environment variable, for purposes of determining whether to run a set of specs.

The workaround makes the command to ignore acceptance specs that are designed to only be run locally directly in the Buildkite config. Not that great a solution, but not terrible, and it pushes the app over the upgrade line.

Edit: @qantas-kd [saved the day](https://github.com/hooroo/sqs_worker/pull/15#issuecomment-1150508364).

### CODE REVIEW

**Comment by ClementineOldfield** [comment]
I'm confused on one point, but overall it looks good.

**Comment by paulfioravanti** [comment]
> I'm confused on one point, but overall it looks good.

Which point, @ClementineOldfield? If you're confused, someone else may be as well, so I'll either have to make a change, or perhaps add in some documentation to make things clearer.

**Review by qantas-kd — APPROVED** [review]
LGTM!

**Comment by qantas-kd** [comment]
Response from buildkite

>Ah yes this is the docker issue I mentioned. That step is using the docker-compose plugin which is not propagating the parent environment through to the docker process. So your tests don't see `CI` because it doesn't exist.
You can check the docs for this plugin for more info on this: [https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#environment](https://urldefense.com/v3/__https://github.com/buildkite-plugins/docker-compose-buildkite-plugin*environment__;Iw!!PUxuPyJo!1_H_4tAqp75pFcy6rlk5YNFB-cm5-EFBJEu2weFTzP9A9r2dp6pxysANfnhq8dikP_xhuc1VYxJJLhiShFFQZOs$). You basically need to allow-list which env vars to pass through to the container.

**Comment by paulfioravanti** [comment]
@qantas-kd Oh, you reached out to Buildkite about this, or did you come across it in another repo? Regardless, I'll give this a try and see if it works before merging in! Thanks! 🎉

**Comment by qantas-kd** [comment]
> @qantas-kd Oh, you reached out to Buildkite about this, or did you come across it in another repo? Regardless, I'll give this a try and see if it works before merging in! Thanks! tada

Yes, I can confirm it works now
https://buildkite.com/hooroo/sqs-worker-dot-gem/builds/154#0181459c-459f-4c13-abff-9e693e6e1f4c
```ruby


SqsWorker::Batcher#process when not shutting down test ci ken ding2
--
  | Failure/Error: expect(ENV['CI']).to eq(true)
  |  
  | expected: true
  | got: "true"
  |  
  | (compared using ==)
  |  
  | Diff:
  | @@ -1 +1 @@
  | -true
  | +"true"

```

**Comment by ClementineOldfield** [comment]
> > I'm confused on one point, but overall it looks good.
> 
> Which point, @ClementineOldfield? If you're confused, someone else may be as well, so I'll either have to make a change, or perhaps add in some documentation to make things clearer.

Sorry Paul I made a separate comment in the code which is what I was referring to. 

"What about upgrading to ruby 2.7 makes the queues unable to run in CI?"

**Pull request merged**
